### ISSUE TITLE
failed to find BuildTools23.0.0 rc2

### ISSUE THREAD

**Issue by wenqiangtxc** [tianzhijiexian/AppBar#1]
用AS打开项目，提示“failed to find BuildTools23.0.0 rc2”，
去更新BuildTools，发现最新的已经是rc3了，更新后改了gradle.build里的BuildToolsVersion，ReBuild Project还是这个错误。
原来导别的项目更改BuildToolsVersion也不行，是还要修改别的地方吗？求指教
建议作者用正式版的BuildTools

**Comment by kaleai** [comment]
其实解决这个问题很简单，你既然已经更新了RC3，又报错RC2找不到，那么说明你导入的这个工程中用到了RC2.我的项目中又app和lib两个module，两个都用到了RC2，你如果只改了一个是不行的，需要两个全部修改。修改的方式也很简单，直接ctrl+alt+shift+s，或者在as的工具栏中点击project structure就可以用图形界面的方式进行修改build tools版本啦。如果这个解决了您的问题，可以close this issue。thx

**Comment by kaleai** [comment]
不知道你的问题有没有解决，如果没有，可以继续提问

**Comment by wenqiangtxc** [comment]
谢谢 已经解决了
